### ISSUE TITLE
avg_size array in denseNet_Localization.py

### ISSUE THREAD

**Issue by hugokitano** [thtang/CheXNet-with-localization#13]
What does the avg_size array in the bounding box procedure represent, and how did you retrieve it? Thanks!

**Comment by thtang** [comment]
It's somehow tricky. Since this task is weekly supervised, no bounding box should be used in the training procedure. However, to make the coverage score (Intersection Of Union) higher, we provide the algo a prior knowledge, i.e., the average size of the bounding box, and generate reasonable results.

**Comment by hugokitano** [comment]
Thanks for answering! I understand. One other thing: I noticed the weights for each training batch are not used. How did you incorporate them in training? I read in your report that your mean AUC ended up being better with them.

**Comment by hugokitano** [comment]
reupping this, thanks

**Comment by Aliktk** [comment]
@hugokitano  how you generate a heatmap for a new image any new image for a patient.
like I get this and then want a heatmap of this image but it shows the only prediction which is also confusing.

`00000003_000.png 18`
`Atelectasis 411.8 512.5 219.0 139.1`
`Atelectasis 276.0 312.0 216.0 136.0`
`Atelectasis 524.0 308.0 216.0 136.0`
`Cardiomegaly 348.5 392.3 479.8 381.1`
`Cardiomegaly 64.0 320.0 476.0 380.0`
`Effusion 396.5 415.8 221.6 318.0`
`Effusion 656.0 96.0 220.0 316.0`
`Infiltration 394.5 389.1 294.0 297.4`
`Infiltration 104.0 100.0 292.0 296.0`
`Infiltration 108.0 620.0 292.0 296.0`
`Mass 434.3 366.7 168.7 189.8`
`Mass 164.0 156.0 168.0 188.0`
`Mass 300.0 668.0 168.0 188.0`
`Nodule 502.4 458.7 71.9 70.4`
`Nodule 64.0 732.0 68.0 68.0`
`Pneumonia 378.7 416.7 276.5 304.5`
`Pneumothorax 369.3 209.4 198.9 246.0`
`Pneumothorax 284.0 644.0 196.0 244.0`

2nd how to generate a heatmap for it and then getting the BB for the actual and predicted image?
if BB is generated using `densenet_localization.py`  then why it predicted 8 to 16 predictions per image? i think it getting 16 predictions which are not possible in a single image right?


Please help dear I will b very  thankfull
