### ISSUE TITLE
loading non existent file 'train_X_small.npy'

### ISSUE THREAD

**Issue by EyalRozenberg1** [thtang/CheXNet-with-localization#4]
the file 'train_X_small.npy' is loaded from [path of preprocessed output (folder)], but it was never created.
should it be downloaded from somewhere?

https://github.com/thtang/CheXNet-with-localization/blob/72a91f13c61bb470c69d912de055f5aed7bc8411/train.py#L38

**Comment by thtang** [comment]
After running the `preprocessing.py` , you would receive `.npy` files for training.

**Comment by EyalRozenberg1** [comment]
yes

But you must name the file because it will be run over by the validation
.npy file

maybe something like:

np.save(data_path + '/train_X_small', train_X)

np.save(data_path + '/valid_X_small', train_X)



2018-06-11 11:30 GMT+03:00 T.H. Tang <notifications@github.com>:

**Comment by thtang** [comment]
Yup, I've fixed it. Thanks

**Comment by EyalRozenberg1** [comment]
👍

2018-06-11 11:48 GMT+03:00 T.H. Tang <notifications@github.com>:
