### ISSUE TITLE
ValueError: Target and input must have the same number of elements

### ISSUE THREAD

**Issue by EyalRozenberg1** [thtang/CheXNet-with-localization#5]
calculating loss between tensors that don't have the same size of elements
outputs & labels_sub
[64,8] & [64,7]

ValueError: Target and input must have the same number of elements. target nelement (448) != input nelement (512)

https://github.com/thtang/CheXNet-with-localization/blob/a5c0c8b05cc6a1d8b3b527a1882100d770ad2f5b/train.py#L170

**Comment by thtang** [comment]
Modify N_CLASSES  for your application.

**Comment by EyalRozenberg1** [comment]
My mistake!
Thanks

2018-06-11 16:10 GMT+03:00 T.H. Tang <notifications@github.com>:
