### ISSUE TITLE
How to run this on a single image ?

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [thtang/CheXNet-with-localization#6]
I want to use this model and run it on a single image say 'xray.jpeg'. What needs to be done ?

**Comment by thtang** [comment]
`python3 denseNet_localization.py [path to test.txt] [path of images folder]`

`[path to test.txt]`: test.txt contains the image file name, i.e., xray.jpeg
`[path of images folder]`: path to the folder you store that image

**Comment by Aliktk** [comment]
@thtang how to visualize the heatmap and BB for the predicted output of the given image?
Furthermore, I am confused why this model always predicts 8 or 16 or 14 predictions in an image which is not possible to find these abnormalities.
So what abnormalities we should focus on to print BB on the heatmap-generated images?
Please help me in this regard
